### ISSUE TITLE
How to define environment variables within jetbrains-flatpak-wrapper?

### ISSUE THREAD

**Issue by x80486** [Lctrs/jetbrains-flatpak-wrapper#2]
I'm trying to use this wrapper with `IDEA Ultimate`. `zypak wrapper` is giving some trouble with some plugins, so I will end up using a custom `idea.properties` file to add/override some of the settings.

`IDEA` is able to override those values by making use of different locations: https://intellij-support.jetbrains.com/hc/en-us/articles/207240985-Changing-IDE-default-directories-used-for-config-plugins-and-caches-storage

Problem is that I can't find a way to declare environment variables here:

```yaml
- name: jetbrains-flatpak-wrapper
  buildsystem: meson
  config-opts:
    - -Deditor_binary=/app/extra/IDEA-U/bin/idea.sh
    - -Deditor_title=IntelliJ IDEA Ultimate
    - -Dprogram_name=idea
  sources:
    - type: dir
      path: jetbrains-flatpak-wrapper
```

...so I can just do `IDEA_PROPERTIES=/app/bin/idea.properties`.

I can probably get around using `--env` with  `finish-args`, but I guess it would be great if there was a key for just that, or if `config-opts` could accept as well `--env`.
